### ISSUE TITLE
Create header for technologies

### ISSUE THREAD

**Issue by SantiagoTettamanti** [SantiagoTettamanti/santiagoportfolio#9]

**Comment by andresmonc** [comment]
float css code; palce this in santiagoportfolio/src/styles.css so that it can be reused
```
@keyframes float {
	0% {
		box-shadow: 0 5px 15px 0px rgba(0,0,0,0.6);
		transform: translatey(0px);
	}
	50% {
		box-shadow: 0 25px 15px 0px rgba(0,0,0,0.2);
		transform: translatey(-20px);
	}
	100% {
		box-shadow: 0 5px 15px 0px rgba(0,0,0,0.6);
		transform: translatey(0px);
	}
}

.float {
	animation: float 6s ease-in-out infinite;
}
```

**Comment by andresmonc** [comment]
https://fonts.google.com/specimen/Bungee+Inline?preview.text=Technologies&preview.text_type=custom&preview.size=36&category=Display

https://fonts.google.com/specimen/Bungee+Shade?preview.text=Technologies&preview.text_type=custom&preview.size=36&category=Display

https://fonts.google.com/specimen/Monofett?preview.text=Technologies&preview.text_type=custom&preview.size=36&category=Display

https://fonts.google.com/specimen/Bungee+Outline?preview.text=Technologies&preview.text_type=custom&preview.size=36&category=Display

**Comment by andresmonc** [comment]
text-shadow: 0 0 .5em rgba(255, 255, 255, .4), 0 0 .2em rgba(0, 0, 0, .3), 0 .5em .5em rgba(0, 0, 0, .3);

**Comment by andresmonc** [comment]
0%      text-shadow: 0 0 .5em rgba(255, 255, 255, .4), 0 0 .2em rgba(0, 0, 0, .3), 0 .3em .2em rgba(0, 0, 0, .3);
100%  text-shadow: 0 0 .5em rgba(255, 255, 255, .4), 0 0 .2em rgba(0, 0, 0, .3), 0 .5em .5em rgba(0, 0, 0, .3);
